vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: uploads/images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: True
            delete_on_update: True

